/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Services.module.css";
import ServiceItem from "./ServiceItem";

const servicesData = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/cc2ca46fa91fa2ba4639a08d7c2adb7c3c274f1caedf6c7f7f92023c9088e381?placeholderIfAbsent=true&apiKey=f68351809d1b498a88d39fd40ad3ba29",
    title: "Application Development",
    description:
      "Standard designing, building, and implementing your applications with documentation.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/81c6301e61254b44b4e7624e9bcb647998a1b302e5f565584aae356fe5301db9?placeholderIfAbsent=true&apiKey=f68351809d1b498a88d39fd40ad3ba29",
    title: "Web Development",
    description:
      "Create and maintain your websites and also take care of its performance and traffic capacity.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/81c6301e61254b44b4e7624e9bcb647998a1b302e5f565584aae356fe5301db9?placeholderIfAbsent=true&apiKey=f68351809d1b498a88d39fd40ad3ba29",
    title: "Data",
    description:
      "Create and maintain your websites and also take care of its performance and traffic capacity.",
  },
];

const Services = () => {
  return (
    <section className={styles.services}>
      <div className={styles.container}>
        <div className={styles.header}>
          <div className={styles.aboveTitleLine} />
          <p className={styles.aboveTitle}>SERVICES</p>
        </div>
        <h2 className={styles.title}>Specialized in</h2>
        <div className={styles.items}>
          {servicesData.map((service, index) => (
            <ServiceItem key={index} {...service} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Services;
