/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Education.module.css";
import EducationItem from "./EducationItem";

const educationData = [
  {
    institution: "Kingston university",
    degree: "Master's degree - Software Engineering",
    period: "2019 - 2021",
  },
  {
    institution: "Kingston university",
    degree: "Bachelor's degree - Computer Engineering",
    period: "2015 - 2019",
  },
  {
    institution: "Westminster School",
    degree: "Diploma's degree - Mathematics",
    period: "2013 - 2015",
  },
];

const Education = () => {
  return (
    <section className={styles.education}>
      <div className={styles.header}>
        <div className={styles.aboveTitleLine} />
        <p className={styles.aboveTitle}>LEARNING PATH</p>
      </div>
      <h2 className={styles.title}>Education & Skills</h2>
      <div className={styles.content}>
        <div className={styles.educationList}>
          {educationData.map((item, index) => (
            <EducationItem key={index} {...item} />
          ))}
        </div>
        <div className={styles.timeline} />
      </div>
    </section>
  );
};

export default Education;
