/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Hero.module.css";

const Hero = () => {
  return (
    <section className={styles.hero}>
      <div className={styles.content}>
        <p className={styles.aboveTitle}>HI, I'M</p>
        <h1 className={styles.name}>
          Tony <span className={styles.highlight}>Jin.</span>
        </h1>
        <p className={styles.description}>
          Creative front-end developer with more than +5 years of experience in
          enterprise companies and startups.
        </p>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/4dd541e2dee0e5b559459112e1e52714c906125850e7dc3236877b7ddfbdcd1c?placeholderIfAbsent=true&apiKey=f68351809d1b498a88d39fd40ad3ba29"
          alt="Social media icons"
          className={styles.socialIcons}
        />
      </div>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/ef7df4c5521478cafc0c2485d36fd6082f1a64275171c49398eccf41a852a096?placeholderIfAbsent=true&apiKey=f68351809d1b498a88d39fd40ad3ba29"
        alt="Tony Jin"
        className={styles.heroImage}
      />
    </section>
  );
};

export default Hero;
