/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./PortfolioItem.module.css";

const PortfolioItem = ({ title, tag, image }) => {
  return (
    <div className={styles.portfolioItem}>
      <div className={styles.imageContainer}>
        {/* Placeholder for portfolio item image */}
      </div>
      <div className={styles.details}>
        <h3 className={styles.title}>{title}</h3>
        <div className={styles.tagContainer}>
          <span className={styles.tag}>{tag}</span>
          <img src={image} alt="" className={styles.tagIcon} />
        </div>
      </div>
    </div>
  );
};

export default PortfolioItem;
