/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "../../components/Layout/Layout";
import Hero from "../../components/Hero/Hero";
import Services from "../../components/Services/Services";
import Portfolio from "../../components/Portfolio/Portfolio";
import Experience from "../../components/Experience/Experience";
import Testimonial from "../../components/Testimonial/Testimonial";
import Education from "../../components/Education/Education";
import Skills from "../../components/Skills/Skills";
import ContactForm from "../../components/ContactForm/ContactForm";

const Home = () => {
  return (
    <Layout>
      <Hero />
      <Services />
      <Portfolio />
      <Experience />
      <Education />
      <ContactForm />
    </Layout>
  );
};

export default Home;
