/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../Header/Header";
import Footer from "../Footer/Footer";
import styles from "./Layout.module.css";

const Layout = ({ children, scrollToSection }) => {
  return (
    <div className={styles.layout}>
      <Header scrollToSection={scrollToSection} />
      <main className={styles.main}>{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
