/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Navigation.module.css";

const Navigation = () => {
  return (
    <nav className={styles.navigation}>
      <a href="#services" className={styles.navLink}>
        Services
      </a>
      <a href="#portfolios" className={styles.navLink}>
        Portfolios
      </a>
      <a href="#experience" className={styles.navLink}>
        Experience
      </a>
      <a href="#blog" className={styles.navLink}>
        Blog
      </a>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/87e3a7a588406bd0740424439e34014ba0f1e28b3f1609631e4ef3092894bccd?placeholderIfAbsent=true&apiKey=f68351809d1b498a88d39fd40ad3ba29"
        alt=""
        className={styles.navIcon}
      />
    </nav>
  );
};

export default Navigation;
