/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Navigation.module.css";

const Navigation = () => {
  return (
    <nav className={styles.navigation}>
      <a href="#services" className={styles.navLink}>
        Services
      </a>
      <a href="#portfolios" className={styles.navLink}>
        Portfolios
      </a>
      <a href="#experience" className={styles.navLink}>
        Experience
      </a>
      <a href="#education" className={styles.navLink}>
        Education
      </a>
      <a href="#contacts" className={styles.navLink}>
        Contacts
      </a>
    </nav>
  );
};

export default Navigation;
