/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ContactForm.module.css";

const ContactForm = () => {
  return (
    <section className={styles.contactForm}>
      <form className={styles.form}>
        <input
          type="text"
          placeholder="Name"
          className={styles.input}
          aria-label="Name"
        />
        <input
          type="email"
          placeholder="Email"
          className={styles.input}
          aria-label="Email"
        />
        <textarea
          placeholder="Message"
          className={styles.textarea}
          aria-label="Message"
        ></textarea>
        <button type="submit" className={styles.submitButton}>
          Send Message
        </button>
      </form>
      <div className={styles.contactInfo}>
        <div className={styles.infoItem}>
          <div className={styles.icon}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/33db8a2230e90d775c6794ece2ac479312b0c3ad0023f3c9787e625c4168a63a?placeholderIfAbsent=true&apiKey=f68351809d1b498a88d39fd40ad3ba29"
              alt=""
              className={styles.iconImage}
            />
          </div>
          <div className={styles.infoContent}>
            <h3 className={styles.infoTitle}>Address</h3>
            <p className={styles.infoText}>
              3424 Layman Avenue, Fayetteville, NC
            </p>
          </div>
        </div>
        <div className={styles.infoItem}>
          <div className={styles.icon}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/3d2331fcd998aca355c1c6e0a7b26bd7cbe93c971edce00395788b9249d68482?placeholderIfAbsent=true&apiKey=f68351809d1b498a88d39fd40ad3ba29"
              alt=""
              className={styles.iconImage}
            />
          </div>
          <div className={styles.infoContent}>
            <h3 className={styles.infoTitle}>Phone</h3>
            <p className={styles.infoText}>(501) 414-1541</p>
          </div>
        </div>
        <div className={styles.infoItem}>
          <div className={styles.icon}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/8e8d9b8af5fca77f846d9b5984664569edb16bcc95219e2b7125752885f578d5?placeholderIfAbsent=true&apiKey=f68351809d1b498a88d39fd40ad3ba29"
              alt=""
              className={styles.iconImage}
            />
          </div>
          <div className={styles.infoContent}>
            <h3 className={styles.infoTitle}>E-Mail</h3>
            <p className={styles.infoText}>devchapter@gmail.com</p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default ContactForm;
