/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Experience.module.css";
import ExperienceItem from "./ExperienceItem";

const experienceData = [
  {
    company: "a",
    position: "Front-end Developer",
    location: "California, United States",
    period: "a",
    tags: ["Swift", "Go"],
    responsibilities: [""],
  },
];

const Experience = () => {
  return (
    <section className={styles.experience}>
      <div className={styles.container}>
        <div className={styles.sidebar}>
          <div className={styles.header}>
            <div className={styles.aboveTitleLine} />
            <p className={styles.aboveTitle}>career path</p>
          </div>
          <h2 className={styles.title}>Work Experiences</h2>
          <div className={styles.companyList}>
            <button className={styles.companyButton}>
              Apple
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/cca51eb5c9fbc81de644342e432b34aca3567585850ba65854afcd26eca24d9d?placeholderIfAbsent=true&apiKey=f68351809d1b498a88d39fd40ad3ba29"
                alt=""
                className={styles.companyIcon}
              />
            </button>
            <button className={styles.companyButton}>Microsoft</button>
            <button className={styles.companyButton}>Facebook</button>
            <button className={styles.companyButton}>Slack</button>
          </div>
        </div>
        <div className={styles.content}>
          {experienceData.map((experience, index) => (
            <ExperienceItem key={index} {...experience} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Experience;
