/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Experience.module.css";
import ExperienceItem from "./ExperienceItem";

const experienceData = [
  {
    company: "Slopedia",
    position: "Full-stack Developer",
    location: "Remote, USA",
    period: "Jan 2024 - Mar 2024",
    tags: ["React.js", "SQL"],
    responsibilities: [
      "Conducted code reviews via GitHub pull requests, ensuring code quality and adherence to best practices.",
      "Created responsive front-end solutions using React.js and Tailwind CSS, and actively participated in team meetings.",
    ],
  },
  {
    company: "Slopedia",
    position: "Full-stack Developer",
    location: "Remote, USA",
    period: "Jan 2024 - Mar 2024",
    tags: ["React.js", "SQL"],
    responsibilities: [
      "Conducted code reviews via GitHub pull requests, ensuring code quality and adherence to best practices.",
      "Created responsive front-end solutions using React.js and Tailwind CSS, and actively participated in team meetings.",
    ],
  },
  {
    company: "Slopedia",
    position: "Full-stack Developer",
    location: "Remote, USA",
    period: "Jan 2024 - Mar 2024",
    tags: ["React.js", "SQL"],
    responsibilities: [
      "Conducted code reviews via GitHub pull requests, ensuring code quality and adherence to best practices.",
      "Created responsive front-end solutions using React.js and Tailwind CSS, and actively participated in team meetings.",
    ],
  },
];

const Experience = () => {
  [currentExpierence, setCurrentExpierence] = useContex;
  return (
    <section className={styles.experience}>
      <div className={styles.header}>
        <div className={styles.aboveTitleLine} />
        <p className={styles.aboveTitle}>career path</p>
      </div>
      <h2 className={styles.title}>Work Experiences</h2>
      <div className={styles.container}>
        <div className={styles.sidebar}>
          <div className={styles.companyList}>
            <button className={styles.companyButton}>
              Slopedia
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/cca51eb5c9fbc81de644342e432b34aca3567585850ba65854afcd26eca24d9d?placeholderIfAbsent=true&apiKey=f68351809d1b498a88d39fd40ad3ba29"
                alt=""
                className={styles.companyIcon}
              />
            </button>
            <button className={styles.companyButton}>Fileread AI</button>
            <button className={styles.companyButton}>
              Jisan Research Institute
            </button>
          </div>
        </div>
        <div className={styles.content}>
          {experienceData.map((experience, index) => (
            <ExperienceItem key={index} {...experience} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Experience;
