/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ThemeToggle.module.css";

const ThemeToggle = () => {
  return (
    <button className={styles.themeToggle} aria-label="Toggle theme">
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/ccaf02fe4bce4e77c9ef700caed7485dcf4253eb1f54d133a53e9bacadbda54e?placeholderIfAbsent=true&apiKey=f68351809d1b498a88d39fd40ad3ba29"
        alt=""
        className={styles.toggleIcon}
      />
    </button>
  );
};

export default ThemeToggle;
